[package]
name = "emoji-remover"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.2"
walkdir = "2.5.0"
clap = { version = "4.5", features = ["derive"] }
glob = "0.3.3"
thiserror = "2.0.17"

